name: "Update Bot"
on:
  schedule:
    - cron: '0 1,13 * * *' # run the bot twice a day at 0100 and 1300 UTC
  push: # also run the action when something on a new commit
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  blog-updates:
    name: bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
    
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
          
      - name: Cache packages
        uses: actions/cache@v3
        with:
        path: |
          ${{ env.R_LIBS_USER }}
          ~/.local/share/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

      - name: Create system dependencies hash
        id: sys-deps-hash
        run: |
          echo "hash=$(echo libcurl4-openssl-dev | md5sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - name: Cache system dependencies
        uses: actions/cache@v3
        id: cache-sys-deps
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-sys-deps-${{ steps.sys-deps-hash.outputs.hash }}
      
      # these dependencies are needed for pak to install packages
      - name: System dependencies
        if: steps.cache-sys-deps.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update

      - name: Initialize renv
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          if (!file.exists("renv.lock")) {
          renv::init(force = TRUE)
          } else {
            renv::restore()
          }
          
      - name: Install dependencies
        shell: Rscript {0}
        run: |
          renv::install(c("jsonlite", "dplyr"))
          deps <- setdiff(unique(renv::dependencies(".")$Package), c("jsonlite", "dplyr"))
          renv::install(deps)
          renv::install("JBGruber/atrrr")
          renv::snapshot()
        
        # after all the preparation, it's time to run the bot
      - name: "Bot - Run"
        run: Rscript 'bot.R'
        env:
          ATR_PW: ${{ secrets.ATR_PW }} # to authenticat, store your app pw as a secret
          
        # after 60 days without a commit, the bot is disabled by GitHub. keepalive-workflow 
        # prevents that
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@2.0.7
