name: "Update Bot"
on:
  schedule:
    - cron: '0 1,13 * * *' # run the bot twice a day at 0100 and 1300 UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  blog-updates:
    name: bot
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
          
      - name: Install renv
        run: |
          install.packages('renv')
          renv::init(force = TRUE)
        shell: Rscript {0}
      
      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      # Cache Ubuntu dependencies    
      - name: Cache system dependencies
        uses: actions/cache@v4
        id: cache-sys-deps
        with:
          path: ~/.apt-cache
          key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-packages.txt') }}
      
      # Install Ubuntu dependencies
      - name: Install system dependencies
        if: steps.cache-sys-deps.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
          mkdir -p ~/.apt-cache
          sudo cp /var/cache/apt/archives/*.deb ~/.apt-cache/
      
      # Restore Ubuntu dependencies
      - name: Restore system dependencies
        if: steps.cache-sys-deps.outputs.cache-hit == 'true'
        run: |
          sudo cp ~/.apt-cache/*.deb /var/cache/apt/archives/
          sudo apt-get install -y libcurl4-openssl-dev
      
      - name: Restore renv environment
        run: |
          renv::restore()
        shell: Rscript {0}
      
      - name: Install additional R packages
        run: |
          renv::install(c("jsonlite", "dplyr", "JBGruber/atrrr"))
          renv::snapshot()
        shell: Rscript {0}
        
      - name: Run bot
        run: |
          tryCatch({
            source('bot.R')
          }, error = function(e) {
            message('Error in bot.R: ', e$message)
            quit(status = 1)
          })
        shell: Rscript {0}
        env:
          ATR_PW: ${{ secrets.ATR_PW }}
        
      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: r-logs
          path: |
            *.Rout
              
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@2.0.7
        